@apiServer=127.0.0.1:3000
@token={{login.response.body.$.token}}
###
# @name login
POST http://{{apiServer}}/login
Content-Type: application/json

{
    "user_name": "sysadmin",
    "password": "helloadmin"
}


###
GET http://{{apiServer}}/v1/user
Authorization: Bearer {{token}}

###
GET http://{{apiServer}}/v1/user/session
Authorization: Bearer {{token}}
